// Builds lib/icons.generated.ts: a tiny offline subset of Solar Outline icons.
// Add a name to ICONS, run `npm run icons:build`, then use <Icon name="..." />.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { getIcons } from "@iconify/utils";

const require = createRequire(import.meta.url);
const solar = JSON.parse(readFileSync(require.resolve("@iconify-json/solar/icons.json"), "utf8"));

const ICONS = [
  "sun-outline",
  "moon-outline",
  "monitor-outline",
  "home-2-outline",
  "arrow-right-outline",
  "check-circle-outline",
  "copy-outline",
  "palette-outline",
  "settings-outline",
  "danger-triangle-outline",
  "info-circle-outline",
  "close-circle-outline",
  "star-outline",
  "videocamera-record-outline",
  "alt-arrow-down-outline",
  "alt-arrow-up-outline",
  "alt-arrow-right-outline",
  "check-read-outline",
  "close-outline",
  "bell-outline",
  "trash-bin-minimalistic-outline",
  "pen-outline",
  "add-circle-outline",
  "menu-dots-outline",
  "logout-outline",
  "user-circle-outline",
  "chart-outline",
  "upload-outline",
  "play-circle-outline",
  "link-outline",
  "eye-outline",
];

const subset = getIcons(solar, ICONS);
const missing = ICONS.filter((n) => !subset?.icons[n] && !subset?.aliases?.[n]);
if (!subset || missing.length) {
  console.error("Unknown Solar icons:", missing.join(", "));
  process.exit(1);
}

const out = `// GENERATED by scripts/build-icons.mjs. Do not edit.
import type { IconifyJSON } from "@iconify/types";

export const iconCollection = ${JSON.stringify(subset)} as IconifyJSON;

export type IconName = ${ICONS.map((n) => JSON.stringify(n.replace(/-outline$/, ""))).join(" | ")};
`;
writeFileSync(new URL("../lib/icons.generated.ts", import.meta.url), out);
console.log(`Wrote ${ICONS.length} icons`);
