"use client";

import { use, useEffect, useState } from "react";

type Form = { id: string; title: string; promptText: string; incentiveType: "none" | "discount" | "custom"; incentiveValue: string | null; branding: { accentColor?: string }; isActive: boolean; slug: string; pendingSubmissionCount?: number };
type Submission = { id: string; type: "video" | "text"; videoUrl: string | null; text: string | null; customerName: string; customerEmail: string; status: string; createdAt: string };
type Draft = { title: string; promptText: string; incentiveType: "none" | "discount" | "custom"; incentiveValue: string; accentColor: string; isActive: boolean };
const blank: Draft = { title: "", promptText: "", incentiveType: "none", incentiveValue: "", accentColor: "#7c3aed", isActive: true };

export default function CollectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id: spaceId } = use(params); const [forms, setForms] = useState<Form[]>([]); const [draft, setDraft] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [submissions, setSubmissions] = useState<Record<string, Submission[]>>({}); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { try { setLoading(true); const r = await fetch(`/api/spaces/${spaceId}/collection-forms`); if (!r.ok) throw new Error("Could not load collection forms."); setForms((await r.json()).collectionForms || []); } catch (e) { setError(e instanceof Error ? e.message : "Could not load collection forms."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [spaceId]);
  const updateDraft = (key: string, value: string | boolean) => setDraft((d) => ({ ...d, [key]: value }));
  const save = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setSuccess(""); const payload = { title: draft.title, promptText: draft.promptText, incentiveType: draft.incentiveType, incentiveValue: draft.incentiveType === "none" ? null : draft.incentiveValue, branding: { accentColor: draft.accentColor }, isActive: draft.isActive }; const url = editing ? `/api/spaces/${spaceId}/collection-forms/${editing}` : `/api/spaces/${spaceId}/collection-forms`; const r = await fetch(url, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!r.ok) { const data = await r.json().catch(() => null); setError(data?.error?.message || "Could not save form."); return; } setSuccess(editing ? "Form updated." : "Collection form created."); setDraft(blank); setEditing(null); load(); };
  const beginEdit = (form: Form) => { setEditing(form.id); setDraft({ title: form.title, promptText: form.promptText, incentiveType: form.incentiveType, incentiveValue: form.incentiveValue || "", accentColor: form.branding?.accentColor || "#7c3aed", isActive: form.isActive }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const loadSubmissions = async (formId: string) => { const r = await fetch(`/api/spaces/${spaceId}/collection-forms/${formId}/submissions`); if (!r.ok) { setError("Could not load submissions."); return; } const data = await r.json(); setSubmissions((s) => ({ ...s, [formId]: data.submissions || [] })); };
  const review = async (formId: string, submissionId: string, status: "approved" | "rejected") => { setError(""); const r = await fetch(`/api/spaces/${spaceId}/collection-forms/${formId}/submissions/${submissionId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!r.ok) { const data = await r.json().catch(() => null); setError(data?.error?.message || "Could not review submission."); return; } setSuccess(`Submission ${status}.`); loadSubmissions(formId); load(); };
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); setSuccess("Copied to clipboard."); } catch { setError("Could not copy to clipboard."); } };
  return <div className="space-y-6"><div><h2 className="text-xl font-bold">Collect testimonials</h2><p className="text-xs text-muted-foreground">Create links to collect video and written customer feedback.</p></div>{error && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{success && <p role="status" className="rounded-md bg-green-500/10 p-3 text-sm text-green-700">{success}</p>}
    <form onSubmit={save} className="grid gap-4 rounded-xl border bg-card p-5 md:grid-cols-2"><h3 className="md:col-span-2 font-semibold">{editing ? "Edit collection form" : "New collection form"}</h3><label className="text-sm">Title<input required value={draft.title} onChange={(e) => updateDraft("title", e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2" /></label><label className="text-sm">Accent color<input required pattern="#[0-9a-fA-F]{6}" value={draft.accentColor} onChange={(e) => updateDraft("accentColor", e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2" /></label><label className="text-sm md:col-span-2">Prompt<textarea required value={draft.promptText} onChange={(e) => updateDraft("promptText", e.target.value)} className="mt-1 min-h-24 w-full rounded-md border bg-background p-2" /></label><label className="text-sm">Incentive type<select value={draft.incentiveType} onChange={(e) => updateDraft("incentiveType", e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2"><option value="none">None</option><option value="discount">Discount</option><option value="custom">Custom</option></select></label><label className="text-sm">Incentive value<input disabled={draft.incentiveType === "none"} required={draft.incentiveType !== "none"} value={draft.incentiveValue} onChange={(e) => updateDraft("incentiveValue", e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2 disabled:opacity-50" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.isActive} onChange={(e) => updateDraft("isActive", e.target.checked)} /> Accept submissions</label><div className="flex gap-2"><button className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{editing ? "Save changes" : "Create form"}</button>{editing && <button type="button" onClick={() => { setEditing(null); setDraft(blank); }} className="rounded-md border px-4 py-2 text-sm">Cancel</button>}</div></form>
    {loading ? <p className="text-sm text-muted-foreground">Loading forms…</p> : forms.map((form) => { const link = typeof window === "undefined" ? "" : `${window.location.origin}/collect/${form.slug}`; const embed = `<iframe src="${link}" width="100%" height="720" frameborder="0" title="${form.title}"></iframe>`; const formSubmissions = submissions[form.id]; return <section key={form.id} className="space-y-4 rounded-xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{form.title}</h3><p className="text-xs text-muted-foreground">{form.isActive ? "Active" : "Inactive"} · {form.pendingSubmissionCount || 0} pending</p></div><div className="flex gap-2"><button onClick={() => beginEdit(form)} className="rounded-md border px-3 py-1.5 text-sm">Edit</button><button onClick={() => loadSubmissions(form.id)} className="rounded-md border px-3 py-1.5 text-sm">{formSubmissions ? "Refresh reviews" : "Review submissions"}</button></div></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs">Share link<div className="mt-1 flex"><input readOnly value={link} className="min-w-0 flex-1 rounded-l-md border bg-muted p-2" /><button onClick={() => copy(link)} className="rounded-r-md border border-l-0 px-3">Copy</button></div></label><label className="text-xs">Embed snippet<div className="mt-1 flex"><input readOnly value={embed} className="min-w-0 flex-1 rounded-l-md border bg-muted p-2" /><button onClick={() => copy(embed)} className="rounded-r-md border border-l-0 px-3">Copy</button></div></label></div>{formSubmissions && <div className="space-y-3 border-t pt-4">{formSubmissions.length === 0 ? <p className="text-sm text-muted-foreground">No submissions yet.</p> : formSubmissions.map((submission) => <article key={submission.id} className="rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{submission.customerName} <span className="font-normal text-muted-foreground">{submission.customerEmail}</span></p><span className="text-xs capitalize text-muted-foreground">{submission.status}</span></div>{submission.type === "video" && submission.videoUrl ? <video controls src={submission.videoUrl} className="mt-3 max-h-72 w-full rounded" /> : <p className="mt-3 whitespace-pre-wrap text-sm">{submission.text}</p>}{submission.status === "pending" && <div className="mt-3 flex gap-2"><button onClick={() => review(form.id, submission.id, "approved")} className="rounded-md bg-primary px-3 py-1.5 text-sm text-primary-foreground">Approve</button><button onClick={() => review(form.id, submission.id, "rejected")} className="rounded-md border px-3 py-1.5 text-sm">Reject</button></div>}</article>)}</div>}</section>; })}</div>;
}
